[env]
TARGET = "x86_64-haruos"
BIN = "target/${TARGET}/${MODE}/bootimage-haruos.bin"

[env.development]
MODE = "debug"

[env.production]
MODE = "release"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.kernel]
command = "cargo"
args = ["xbuild"]

[tasks.build]
command = "cargo"
args = ["bootimage"]
dependencies = ["kernel"]

[tasks.qemu]
command = "qemu-system-x86_64"
args = [
    "-drive",
    "format=raw,file=${BIN}",
]

[tasks.test]
command = "cargo"
args = ["xtest"]

[tasks.rebuild]
dependencies = [
    "clean",
    "build",
]

[tasks.run]
dependencies = [
    "build",
    "qemu"
]
